---
- name: Run a shell command on localhost
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Execute a shell command
      shell: "ping -c 4 {{ target_host }}"
      register: ping_output

    - name: Ouput ping result
      debug:
        msg: "The ping output was: {{ ping_output.stdout }}"
